sudo: required
services:
- docker
language: go
go:
- '1.10'

after_success:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=mcasimir/regsecret-operator
- docker build -f Dockerfile -t $REPO:latest .
- docker tag $REPO:latest $TRAVIS_TAG
- docker push $REPO

env:
  global:
  - secure: TepnKEVvKEeAiVbbRZh+LMw1OV6i0AqAVar0LJEi65FVgRn0gdoQGfvG2p9hI4xv1By4dp9bXJ0nteCqbEa1MVixC8oc9eJqD0W9GwyGGvAZ+ovIEtcLB1qbj3e+wdr70tLiVelxjoNlKBiF0N04Aa/9mnovRe2iQ+fiKJX/DYLD53r3Pfx+uWxjEbVYf+1OaxfL1lnJrJvjjn3nALogXOli5EA0OsGF+uzFXoDSKH1C0sefeM7pWiii+ZgyLDHL6oKN2Hh/Jdw16TMXex9EscwgEtaivxieqvnwycOpFGy2INrTAzeomU2Hhfwzqftb34axyaSbq4yngrOTJbpcl2Xxwgg3lnaGTsiNhg0hGztgnSz7UZF7ACzRahZ8uDfCmaxHSxw2V3XkiDsU9ubEfaCZgidVkLLSyp7GdQW8byaskAW0n9E+2kVPxf4mmHZVuVAFrfuscN1IJdhXgX4L/TkDVHWpn50yTOKtf8qYEGO3MHMRPF07P+bAaR0kkf8b2/O0PEMvLOlCMXBkZi6+j+ae8oneyBLDYdYVkhSPfwooenW3PS808qAv9xGo0y0qdGsG54Uoxr7xK+AqiucThcv3CvrRSp2KhrUm+Mix1a+YSEsFplrIOZiPPrBkVlr/IqLg4IhGCrzfFilsgENFsoX8zk27LElL8jwoplYtZUo=
  - secure: eD/xW2THj05BCGBnr+DhMv55tzVO4+BLaRTDXEDYqxMYpQOJ5nolyraaPZML8aDGVhd+eXkQZuGTAO5pQ1/Jd6DVbPl4CeuJvUg4v+jFllCg7qYgQ6QE2dfa0D3GCFYaONCARWCmmyLl6xi+8QOhzfoACAjwV/3dV8oewCwD5Au4v9ehKRy2d4VqsQWDYCW5O81EcJFosQHx8ui4I7QVasmCZ/5e2Nr7vvGDqWVEvLozQY4w9KgS8YXb9tcjPXi4epLQ+Emf5bXavWb1p/xenSEL0ZeN1oBIvzVpoJXAlsrKBDitN5zYd1eJ3mTn3F3KIckLnFWjJoEl0RjZTnN3x1MkTh4kDuBwNikawLVDbeXEO3Vv4X7FSMkfGO4FWjxZZ1uSB+uI3I5ZxPY636NXdtDv6LIrWMZNZjlRX9vqBsXNuvS1vGckNHiGpBH7F1nHcgk/E2B8BK93VWsK2SQqY/7pXu7HpuC31X3tmvi04nfucdpb/kKnzV+5Vm6DDh5YQYPGZTYLoHsLdeTgiFB2qQ9C6fecQirTCftF+rkr9jqCzZOCWvrf3aAbpq+4z1/3o/D7Ct2RUFtPYEvRQOyvKUA75lnzWuycUnRyXMz5zRuTY4sIwD6Qz2ke7k+IJt4Vqv/4V4ARKsOiX1u1JFuhLhbbhwB37VvRIIqSV6X3Ezo=
  - secure: bMu+6zsKw59LENgEDmAnTKQGkF+IwLf6WNUWlQWbsYegYN/roxHY1PS29Dawmer0KAYySrGNPD5eNTDMQTVznFHQg86q3rGd8wS3wQD4cbVTNVawdfM6yR6QeQmgdgAJvRNrDcfkSy0ecRWQxBYhhb7SzbPFpL/Vs9uV6Mnxk8pZ+ETMXi0igVZSA8FJo+sxeCyrAMPiuRf/1BJ7DophcgMZxTRM5gcrCt/o0cKMgpzgOhmlDYtnJNZZcGA104vxAT4GAncQjbze8fvbD6z8jIUQftrg+7Bj2o2LJnokeZgqr3vHC7OKIKIXWZRDgGCSt5Ttu8Judq7SySU/D4vQ2RN6Jy2//Dhn7nS4kHes0ynFwjM6W+fJp0WFl5aM5KlEIB723ea2ZkJVscZU0dFBixVSQt1XZzpnklVa+DYQrM/V1rQ+sHYTLhtxDjlFvVbMfk8r74P6I3DdRKwoeJCFrHHiLbKLIihkRSEeeB39D6AkBhuKuf8Z+B2ZKDtMNOxU2Tk4kELIMCfUpyd1lOEz+8H1/KGzlL1BvpbQXp0jGBmvDvgrm9YClM1iWKFSFfg0hoh1mbM4LR/z/W2VplYdCRIIGvUo11hURkSbEbCnVx5bYmdv1UYtqE6e7wmmJybxr8OKHZNUeuNG1mmM+j3+wvNRXK5aQB7GM6Ssa1M9LTk=
