version: '2.1'

services:
  app:
    build: .
    network_mode: "host"
    volumes:
      - $HOME/.kube/config:/root/.kube/config:ro
    command:
      - ./app
      - --run-outside-cluster
    environment:
      REGSECRET_OPERATOR_CONFIG: >
        {
          "logger": {
            "level": "debug",
            "format": "pretty"
          },
          "secrets": [
            {
              "secretName": "anyone",
              "credentials": {
                "https://index.docker.io/v1/": {
                  "username": "my-username",
                  "password": "my-password",
                  "email": "my-email"
                }
              }
            },
            {
              "namespaceSelector": "owner==dev",
              "secretName": "devs",
              "credentials": {
                "https://index.docker.io/v1/": {
                  "username": "my-username",
                  "password": "my-password",
                  "email": "my-email"
                }
              }
            },
            {
              "namespaceSelector": "owner==sysadmin",
              "secretName": "sysadmins",
              "credentials": {
                "https://index.docker.io/v1/": {
                  "username": "my-username",
                  "password": "my-password",
                  "email": "my-email"
                }
              }
            }
          ]
        }
